FROM debian:12

RUN apt-get update -y && apt-get upgrade -y \
    php-fpm \
    wget \
    php-mysql

RUN wget https://fr.wordpress.org/wordpress-6.0-fr_FR.tar.gz -P /var/www

RUN cd /var/www && tar -xzf wordpress-6.0-fr_FR.tar.gz && rm wordpress-6.0-fr_FR.tar.gz

# RUN	chown -R root:root /var/www/wordpress

COPY tools/config.sh .

CMD ["sh", "./config.sh"]
